//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16:00:00")]
        public global::System.TimeSpan DayFrom {
            get {
                return ((global::System.TimeSpan)(this["DayFrom"]));
            }
            set {
                this["DayFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23:59:59")]
        public global::System.TimeSpan DayTo {
            get {
                return ((global::System.TimeSpan)(this["DayTo"]));
            }
            set {
                this["DayTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan NightFrom {
            get {
                return ((global::System.TimeSpan)(this["NightFrom"]));
            }
            set {
                this["NightFrom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("06:00:00")]
        public global::System.TimeSpan NightTo {
            get {
                return ((global::System.TimeSpan)(this["NightTo"]));
            }
            set {
                this["NightTo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskGetPrih_Type {
            get {
                return ((string)(this["TaskGetPrih_Type"]));
            }
            set {
                this["TaskGetPrih_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskGetPrih_Value {
            get {
                return ((int)(this["TaskGetPrih_Value"]));
            }
            set {
                this["TaskGetPrih_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskPrihAnswer_Type {
            get {
                return ((string)(this["TaskPrihAnswer_Type"]));
            }
            set {
                this["TaskPrihAnswer_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskPrihAnswer_Value {
            get {
                return ((int)(this["TaskPrihAnswer_Value"]));
            }
            set {
                this["TaskPrihAnswer_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskGetOrder_Type {
            get {
                return ((string)(this["TaskGetOrder_Type"]));
            }
            set {
                this["TaskGetOrder_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskGetOrder_Value {
            get {
                return ((int)(this["TaskGetOrder_Value"]));
            }
            set {
                this["TaskGetOrder_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("h")]
        public string TaskOstatki_Type {
            get {
                return ((string)(this["TaskOstatki_Type"]));
            }
            set {
                this["TaskOstatki_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int TaskOstatki_Value {
            get {
                return ((int)(this["TaskOstatki_Value"]));
            }
            set {
                this["TaskOstatki_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public int TaskAdresDelivery_Value {
            get {
                return ((int)(this["TaskAdresDelivery_Value"]));
            }
            set {
                this["TaskAdresDelivery_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskOrderAnswer_Type {
            get {
                return ((string)(this["TaskOrderAnswer_Type"]));
            }
            set {
                this["TaskOrderAnswer_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskOrderAnswer_Value {
            get {
                return ((int)(this["TaskOrderAnswer_Value"]));
            }
            set {
                this["TaskOrderAnswer_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskVzvr_Type {
            get {
                return ((string)(this["TaskVzvr_Type"]));
            }
            set {
                this["TaskVzvr_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskVzvr_Value {
            get {
                return ((int)(this["TaskVzvr_Value"]));
            }
            set {
                this["TaskVzvr_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskVzvr_isActive {
            get {
                return ((bool)(this["TaskVzvr_isActive"]));
            }
            set {
                this["TaskVzvr_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TaskOrderAnswer_isActive {
            get {
                return ((bool)(this["TaskOrderAnswer_isActive"]));
            }
            set {
                this["TaskOrderAnswer_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskAdresDelivery_isActive {
            get {
                return ((bool)(this["TaskAdresDelivery_isActive"]));
            }
            set {
                this["TaskAdresDelivery_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskOstatki_isActive {
            get {
                return ((bool)(this["TaskOstatki_isActive"]));
            }
            set {
                this["TaskOstatki_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskGetOrder_isActive {
            get {
                return ((bool)(this["TaskGetOrder_isActive"]));
            }
            set {
                this["TaskGetOrder_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskGetPrih_isActive {
            get {
                return ((bool)(this["TaskGetPrih_isActive"]));
            }
            set {
                this["TaskGetPrih_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskPrihAnswer_isActive {
            get {
                return ((bool)(this["TaskPrihAnswer_isActive"]));
            }
            set {
                this["TaskPrihAnswer_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dh")]
        public string TaskAdresDelivery_Type {
            get {
                return ((string)(this["TaskAdresDelivery_Type"]));
            }
            set {
                this["TaskAdresDelivery_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskRez_isActive {
            get {
                return ((bool)(this["TaskRez_isActive"]));
            }
            set {
                this["TaskRez_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskRez_Type {
            get {
                return ((string)(this["TaskRez_Type"]));
            }
            set {
                this["TaskRez_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskRez_Value {
            get {
                return ((int)(this["TaskRez_Value"]));
            }
            set {
                this["TaskRez_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TaskSnRez_isActive {
            get {
                return ((bool)(this["TaskSnRez_isActive"]));
            }
            set {
                this["TaskSnRez_isActive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("m")]
        public string TaskSnRez_Type {
            get {
                return ((string)(this["TaskSnRez_Type"]));
            }
            set {
                this["TaskSnRez_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int TaskSnRez_Value {
            get {
                return ((int)(this["TaskSnRez_Value"]));
            }
            set {
                this["TaskSnRez_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskGetPrih_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskGetPrih_LastRun"]));
            }
            set {
                this["TaskGetPrih_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskPrihAnswer_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskPrihAnswer_LastRun"]));
            }
            set {
                this["TaskPrihAnswer_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskGetOrder_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskGetOrder_LastRun"]));
            }
            set {
                this["TaskGetOrder_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskOrderAnswer_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskOrderAnswer_LastRun"]));
            }
            set {
                this["TaskOrderAnswer_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskVzvr_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskVzvr_LastRun"]));
            }
            set {
                this["TaskVzvr_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskOstatki_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskOstatki_LastRun"]));
            }
            set {
                this["TaskOstatki_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskAdresDelivery_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskAdresDelivery_LastRun"]));
            }
            set {
                this["TaskAdresDelivery_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskRez_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskRez_LastRun"]));
            }
            set {
                this["TaskRez_LastRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("01/01/2021 01:00:00")]
        public global::System.DateTime TaskSnRez_LastRun {
            get {
                return ((global::System.DateTime)(this["TaskSnRez_LastRun"]));
            }
            set {
                this["TaskSnRez_LastRun"] = value;
            }
        }
    }
}
