//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cron.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ftp.itsm59.online")]
        public string ftp_host {
            get {
                return ((string)(this["ftp_host"]));
            }
            set {
                this["ftp_host"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1777")]
        public int ftp_port {
            get {
                return ((int)(this["ftp_port"]));
            }
            set {
                this["ftp_port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_PRIH")]
        public string LocalPrihDir {
            get {
                return ((string)(this["LocalPrihDir"]));
            }
            set {
                this["LocalPrihDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_PRIH\\ANSWER")]
        public string LocalPrihAnswerDir {
            get {
                return ((string)(this["LocalPrihAnswerDir"]));
            }
            set {
                this["LocalPrihAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/PRIH/")]
        public string FtpPrihAnswerDir {
            get {
                return ((string)(this["FtpPrihAnswerDir"]));
            }
            set {
                this["FtpPrihAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/PRIH/arhiv/")]
        public string FtpPrihArchivDir {
            get {
                return ((string)(this["FtpPrihArchivDir"]));
            }
            set {
                this["FtpPrihArchivDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/PRIH/")]
        public string FtpPrihDir {
            get {
                return ((string)(this["FtpPrihDir"]));
            }
            set {
                this["FtpPrihDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_PRICE")]
        public string LocalPriceDir {
            get {
                return ((string)(this["LocalPriceDir"]));
            }
            set {
                this["LocalPriceDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/PRICE/")]
        public string FtpPriceDir {
            get {
                return ((string)(this["FtpPriceDir"]));
            }
            set {
                this["FtpPriceDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_ORDER")]
        public string LocalOrderDir {
            get {
                return ((string)(this["LocalOrderDir"]));
            }
            set {
                this["LocalOrderDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_ORDER\\ANSWER")]
        public string LocalOrderAnswerDir {
            get {
                return ((string)(this["LocalOrderAnswerDir"]));
            }
            set {
                this["LocalOrderAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/ORDER/")]
        public string FtpOrderDir {
            get {
                return ((string)(this["FtpOrderDir"]));
            }
            set {
                this["FtpOrderDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/ORDER/")]
        public string FtpOrderAnswerDir {
            get {
                return ((string)(this["FtpOrderAnswerDir"]));
            }
            set {
                this["FtpOrderAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/ORDER/Arhiv/")]
        public string FtpOrderArchivDir {
            get {
                return ((string)(this["FtpOrderArchivDir"]));
            }
            set {
                this["FtpOrderArchivDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_ADRESS")]
        public string LocalAdresDeliveryDir {
            get {
                return ((string)(this["LocalAdresDeliveryDir"]));
            }
            set {
                this["LocalAdresDeliveryDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/ADRES/")]
        public string FtpAdressDir {
            get {
                return ((string)(this["FtpAdressDir"]));
            }
            set {
                this["FtpAdressDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_REZERV")]
        public string LocalRezDir {
            get {
                return ((string)(this["LocalRezDir"]));
            }
            set {
                this["LocalRezDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_REZERV\\ANSWER")]
        public string LocalRezAnswerDir {
            get {
                return ((string)(this["LocalRezAnswerDir"]));
            }
            set {
                this["LocalRezAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/REZERV/")]
        public string FtpRezDir {
            get {
                return ((string)(this["FtpRezDir"]));
            }
            set {
                this["FtpRezDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/REZERV/")]
        public string FtpRezAnswerDir {
            get {
                return ((string)(this["FtpRezAnswerDir"]));
            }
            set {
                this["FtpRezAnswerDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/KRON/REZERV/Архив/")]
        public string FtpRezArchivDir {
            get {
                return ((string)(this["FtpRezArchivDir"]));
            }
            set {
                this["FtpRezArchivDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/KIZ_PRIH/")]
        public string FtpPrihAnswerMdDir {
            get {
                return ((string)(this["FtpPrihAnswerMdDir"]));
            }
            set {
                this["FtpPrihAnswerMdDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pr")]
        public string MaskPrih {
            get {
                return ((string)(this["MaskPrih"]));
            }
            set {
                this["MaskPrih"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ord")]
        public string MaskOrder {
            get {
                return ((string)(this["MaskOrder"]));
            }
            set {
                this["MaskOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("rez")]
        public string MaskRez {
            get {
                return ((string)(this["MaskRez"]));
            }
            set {
                this["MaskRez"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("snrez")]
        public string MaskSnRez {
            get {
                return ((string)(this["MaskSnRez"]));
            }
            set {
                this["MaskSnRez"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/PZ_VZVR/")]
        public string FtpVzvrDir {
            get {
                return ((string)(this["FtpVzvrDir"]));
            }
            set {
                this["FtpVzvrDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\CRON_PZ_VZVR")]
        public string LocalVzvrDir {
            get {
                return ((string)(this["LocalVzvrDir"]));
            }
            set {
                this["LocalVzvrDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/KIZ_ORDER/")]
        public string FtpOrderAnswerMdDir {
            get {
                return ((string)(this["FtpOrderAnswerMdDir"]));
            }
            set {
                this["FtpOrderAnswerMdDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/MED/KIZ_ORDER/")]
        public string FtpOrderAnswerOptDir {
            get {
                return ((string)(this["FtpOrderAnswerOptDir"]));
            }
            set {
                this["FtpOrderAnswerOptDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxx")]
        public string ftp_usr {
            get {
                return ((string)(this["ftp_usr"]));
            }
            set {
                this["ftp_usr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxx")]
        public string ftp_psw {
            get {
                return ((string)(this["ftp_psw"]));
            }
            set {
                this["ftp_psw"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xxx@profitmed.net;zzz@profitmed.net")]
        public string MailTo {
            get {
                return ((string)(this["MailTo"]));
            }
            set {
                this["MailTo"] = value;
            }
        }
    }
}
